### ISSUE TITLE
support lambdas in :bind

### ISSUE THREAD

**Issue by reuleaux** [conao3/leaf.el#466] opened 2020-11-20 22:44 UTC
(I had mentioned this in the discussion on my other issue #464 already,
but I am opening a new issue now, as really this deserves to be considered
on its own, and writing this on the gh website now -- with markdown styling --
it will hopefully be more readable):

Taking your complete example (from my other issue: #464) as a starting point
but adapting it  to exercise _leaf_ on _flycheck_ (not on _ivy_), this code works
fine for me:

 
```elisp
;;; init3.el --- Sample clean init.el  -*- lexical-binding: t; -*-                                                                 

(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(eval-when-compile
  (setq user-emacs-directory
        (expand-file-name (file-name-directory default-directory))))

(eval-and-compile
  (prog1 "leaf"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize)

    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf)))

  (unless (package-installed-p 'leaf-keywords)
    (package-refresh-contents)
    (package-install 'leaf-keywords)
    )

  )



(leaf leaf
  :init
  (leaf leaf-keywords
    :init
    (leaf-keywords-init)
    )

    )

(leaf flycheck


  :bind
  (

  ("C-<f5>" . flycheck-next-error)

  ("C-<f6>" . flycheck-previous-error)


  ;; ( "C-S-<f5>" . (lambda ()                                                                                                    
  ;;                   (progn                                                                                                     
  ;;                    (message "compiling...")                                                                                  
  ;;                    (flycheck-compile flycheck-checker)                                                                       
  ;;                    )                                                                                                         
  ;;                    ))                                                                                                        


  ;; ("C-S-<f6>" . (lambda ()                                                                                                     
  ;;                 (progn                                                                                                       
  ;;                   (message "listing errors")                                                                                 
  ;;                   (flycheck-list-errors)                                                                                     
  ;;                   )                                                                                                          
  ;;                 ))                                                                                                           
  ) ;; bind                                                                                                                       
)
```
I can byte compile this code
```
emacs --batch -f batch-byte-compile init3.el
```
and run it, like so:
```
emacs -q -l init3.elc &
```

Now I would hope, that the code still works, when I _un-comment_ the
two _lambda bindings_ 

```elisp
;;; init4.el --- Sample clean init.el  -*- lexical-binding: t; -*-                                                       

(when load-file-name
  (setq user-emacs-directory
        (expand-file-name (file-name-directory load-file-name))))

(eval-when-compile
  (setq user-emacs-directory
	(expand-file-name (file-name-directory default-directory))))

(eval-and-compile
  (prog1 "leaf"
    (custom-set-variables
     '(package-archives '(("org"   . "https://orgmode.org/elpa/")
                          ("melpa" . "https://melpa.org/packages/")
                          ("gnu"   . "https://elpa.gnu.org/packages/"))))
    (package-initialize)

    (unless (package-installed-p 'leaf)
      (package-refresh-contents)
      (package-install 'leaf)))

  (unless (package-installed-p 'leaf-keywords)
    (package-refresh-contents)
    (package-install 'leaf-keywords)
    )
     
  )  



(leaf leaf
  :init
  (leaf leaf-keywords
    :init
    (leaf-keywords-init)
    )
     
    )

(leaf flycheck


  :bind
  (    
   
  ("C-<f5>" . flycheck-next-error)

  ("C-<f6>" . flycheck-previous-error)


  ( "C-S-<f5>" . (lambda ()
                    (progn
                     (message "compiling...")
                     (flycheck-compile flycheck-checker)
                     )
                     ))


  ("C-S-<f6>" . (lambda ()
                  (progn
                    (message "listing errors")
                    (flycheck-list-errors)
                    )
                  )) 
  ) ;; bind                                                                                                             
)
```

However, this code fails to byte compile for me now:
```
$ emacs --batch -f batch-byte-compile init4.el
Loading /etc/emacs/site-start.d/00debian.el (source)...
Loading /etc/emacs/site-start.d/50auctex.el (source)...
Loading /usr/share/emacs/site-lisp/auctex.el (source)...
Loading /usr/share/emacs/site-lisp/preview-latex.el (source)...
Loading /etc/emacs/site-start.d/50autoconf.el (source)...
Loading /etc/emacs/site-start.d/50dictionaries-common.el (source)...
Loading debian-ispell...
Loading /var/cache/dictionaries-common/emacsen-ispell-default.el (source)...
Loading /var/cache/dictionaries-common/emacsen-ispell-dicts.el (source)...

In toplevel form:
init4.el:41:1:Error: Wrong type argument: listp, "C-S-<f5>"
```
Admittedly, the use of lambdas is a little constructed/artificial here
(just printing a _message_ before calling a function in both cases)
-- to keep the example simple here -- but I have many other (more complicated)
cases of binding lambdas to key sequences, and in _use-package_ this was not
a problem.

And I know: I can define functions for these lambdas -- and I may have to do
this as a workaround for now. But really, I think: lambdas should be supported
in `:bind`. -- Thanks, A

**Comment by conao3** [comment] 2020-11-29 14:59
lambda in `:bind` is not supported for now. Please wait a moment or please contribute to this.
(BTW, please re-format your snippet when paste issue board. It is hard to grasp leaf configuration)

**Comment by conao3** [comment] 2020-11-29 15:07
It is a duplicate of #322. Please move. closing for now.

**Closed by conao3** 2020-11-29 15:07 UTC
